//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int event_id { get; set; }
        public Nullable<int> pig_id { get; set; }
        public Nullable<int> event_type { get; set; }
        public Nullable<bool> event_done { get; set; }
        public Nullable<System.DateTime> event_date { get; set; }
        public Nullable<System.DateTime> event_next_date { get; set; }
        public string description { get; set; }
    
        public virtual Pig_Events Pig_Events { get; set; }
        public virtual Pig Pig { get; set; }
    }
}
