//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.MedicineTransactions = new HashSet<MedicineTransaction>();
        }
    
        public int medicine_id { get; set; }
        public string medicine_name { get; set; }
        public string supplier { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public string description { get; set; }
    
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineTransaction> MedicineTransactions { get; set; }
    }
}
