//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoAn_1Entities : DbContext
    {
        public DoAn_1Entities()
            : base("name=DoAn_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeShift> EmployeeShifts { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<FoodTransaction> FoodTransactions { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<MedicineTransaction> MedicineTransactions { get; set; }
        public virtual DbSet<MonthlyFinancialRecord> MonthlyFinancialRecords { get; set; }
        public virtual DbSet<PenExpense> PenExpenses { get; set; }
        public virtual DbSet<Pig_Events> Pig_Events { get; set; }
        public virtual DbSet<PigMeasurement> PigMeasurements { get; set; }
        public virtual DbSet<PigPen> PigPens { get; set; }
        public virtual DbSet<Pig> Pigs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Salary_history> Salary_history { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<SickPig> SickPigs { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskShift> TaskShifts { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vacine_history> Vacine_history { get; set; }
    }
}
