//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenExpense
    {
        public int expense_id { get; set; }
        public string expense_description { get; set; }
        public Nullable<bool> pig_sell { get; set; }
        public Nullable<decimal> expense { get; set; }
        public System.DateTime expense_date { get; set; }
        public Nullable<int> pen_id { get; set; }
    
        public virtual PigPen PigPen { get; set; }
    }
}
