//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PigMeasurement
    {
        public int measurement_id { get; set; }
        public Nullable<int> pig_id { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<System.DateTime> date_of_measurement { get; set; }
    
        public virtual Pig Pig { get; set; }
    }
}
