//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_history
    {
        public int salary_history_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> month { get; set; }
        public Nullable<decimal> bonus { get; set; }
        public Nullable<decimal> sum_salary { get; set; }
    
        public virtual User User { get; set; }
    }
}
